// Song catalog. Every song gets a stable id and an explicit file field;
// filenames live in Songs/ (capital S — matters on case-sensitive hosts).

const SONGS = [
    { title: "Cameraman", artist: "Kelton ft. Sean" },
    { title: "Chainsaw Man Opening - Kick Back [8 Bit VRC6]", artist: "MegaBaz" },
    { title: "Untitled1", artist: "Unknown Artist" },
    { title: "Rock My Emotions", artist: "Kitsune" },
    { title: "ROBLOX Music - Crossroad Times", artist: "ROBLOX" },
    { title: "Untitled2", artist: "Sean" },
    { title: "April 13", artist: "Sean" },
    { title: "April 14", artist: "Sean" },
    { title: "April 15", artist: "Sean" },
    { title: "Oleana Battle Music - Pokemon Sword and Shield", artist: "Game Freak" },
    { title: "Giorno's Theme (Medieval Style)", artist: "Mystic Zaru" },
    { title: "Faerie's Aire and Death Waltz", artist: "superrainbowderp" },
    { title: "Eccentricity", artist: "Sean" },
    { title: "Team Fortress 2 - Upgrade Station", artist: "Valve Studio Orchestra" },
    { title: "TOKYO DRIFT FREESTYLE", artist: "bbno$" },
    { title: "Sniper Remix Number One TF2", artist: "Mastgrr" },
    { title: "Team Fortress 2 - Your Team Lost", artist: "Valve Studio Orchestra" },
    { title: "Flame On {Human Torch Song}", artist: "Hitman's Beatmaker and Oll Korrect" },
    { title: "Level 6 - City", artist: "Rolling Sky" },
    { title: "Everywhere At The End Of DaBaby", artist: "ynk" },
    { title: "Playing with Christmas", artist: "Mastgrr" },
    { title: "Wii Theme But It's September", artist: "Mr Rock" },
    { title: "Frontier Justice", artist: "Dapper Dog" },
    { title: "TRNDSTTR (Instrumental)", artist: "Black Coast" },
    { title: "Bubble D.Va", artist: "ThatPunchKid" },
    { title: "Feel Good Inc. (Acoustic Cover)", artist: "Luca Stricagnoli, Gorillaz" },
    { title: "PEN BEAT I BATTLE", artist: "Shane Bang" },
    { title: "Sicko Mode (feat. K.K. Slider)", artist: "GameChops" },
    { title: "BFDI-Chapp", artist: "jacknjellify, Jockson" },
    { title: "AVM Ep 16. Note Block - Green's Jam", artist: "AaronGrooves, NeedInBalance" },
    { title: "Kazotsky Makes You Lose Control", artist: "gentu, Missy Elliott" },
    { title: "Flower", artist: "Moby" },
    { title: "There is No Candy in Me", artist: "Baljeet, Jon Colton Barry" },
    { title: "Rock My BFDI", artist: "jacknjellify, Kitsune" },
    { title: "Something-Chapp", artist: "Jockson" },
    { title: "Taunting Makes You Lose Control", artist: "Laurennntiu, Missy Elliott" },
    { title: "A Hat in Time [Seal the Deal] - Death Wish", artist: "Pascal Michael Stiefel" },
    { title: "Demoknight TF2 VS Engineer Gaming", artist: "SilentManJoe, Sock.clip" },
    { title: "MissingNo", artist: "TheInnuendo" },
    { title: "Piano Woman", artist: "Pukklez" },
    { title: "One Steady Roll", artist: "Pisk" },
    { title: "Pokémon Sun and Moon - Guzma Encounter Music", artist: "Game Freak" },
    { title: "Pokémon XY Theme", artist: "Ben Dixon and The Sad Truth" },
    { title: "Tinkerer Island", artist: "JakeTheDrake" },
    { title: "Song That Might Play When You Fight Sans (Acapella)", artist: "Smooth McGroove, Toby Fox" },
    { title: "Flatzone - VS. Kapi", artist: "Paperkitty" },
    { title: "Overhead", artist: "Sock.clip" },
    { title: "Gimme a Grade", artist: "The Baljeatles" },
    { title: "i let my little brother use Fl Studio", artist: "Paerle" },
    { title: "Kindle Kingdom Prediction", artist: "MSM World of Elements, JakeTheDrake" },
    { title: "Not So Bad a Dad", artist: "Olivia Olson" },
    { title: "Embrace the Unexpected - Opera Rap", artist: "Twist of Fate Wines" },
    { title: "Kleptomanie", artist: "Caravan Palace" },
    { title: "Bowgart the Barbarian", artist: "Robert Smith" },
    { title: "Demoman - Beggin'", artist: "Seriamon3, Måneskin" },
    { title: "Floppy Disks - Five Nights at Freddy's 1 Song", artist: "vaser888, The Living Tombstone" },
    { title: "Floppy Drives - Clint Eastwood", artist: "vaser888, Gorillaz" },
    { title: "Floppy Drives - Lone Digger", artist: "vaser888, Caravan Palace" },
    { title: "Dangerous", artist: "Left Boy, Big Data, Joywave" },
    { title: "It's Pizza Time!", artist: "Mr. Sauceman" },
    { title: "Tinkerer Monsters on Magical Nexus", artist: "JakeTheDrake" },
    { title: "what is 1 trillion to the 10th power", artist: "kyuuwaii" },
    { title: "Where Have All The Staplers Gone (Piano Cover)", artist: "Piano Eagle, VeggieTales" },
    { title: "Milkshake", artist: "Caravan Palace" },
    { title: "Chocolate", artist: "Caravan Palace" },
    { title: "Upgrade Station [Bossa Nova _ Big Band Remix]", artist: "Vandoorea" },
    { title: "Ethereal Workshop But I Kidnapped 21 Monsters", artist: "Sean" },
    { title: "Music That Slaps", artist: "Sean" },
    { title: "Cumulus Chase", artist: "Sean" },
    { title: "G Mixolydian", artist: "Sean" },
    { title: "Insomnia", artist: "Sean" },
    { title: "Star Scat - Composer Cover", artist: "Sean, Caravan Palace" },
    { title: "The Flat 7th", artist: "Sean" },
    { title: "The Walker - Composer Cover", artist: "Sean, Fitz and The Tantrums" },
    { title: "Twelve", artist: "Sean" },
    { title: "C Shanty", artist: "Sean" },
    { title: "Castaways - Composer Cover", artist: "Sean, The Backyardigans" },
    { title: "Overhead - Composer Cover", artist: "Sean, Sock.clip" },
    { title: "Plant Island - Composer Cover", artist: "Sean, Big Blue Bubble" },
    { title: "The Isle of Rocks", artist: "Sean, Big Blue Bubble" },
    { title: "Twenty-Two", artist: "Sean" },
    { title: "Une Courte Tristesse", artist: "Sean" },
    { title: "Water is Land", artist: "Sean" },
    { title: "Astronaut in the Ocean - Composer Cover", artist: "Sean, Masked Wolf" },
    { title: "C Dorian - Composer", artist: "Sean" },
    { title: "C Dorian - MuseScore", artist: "Sean" },
    { title: "Chronicles of Junior Year Band", artist: "Sean" },
    { title: "Comme Elle Me Disait", artist: "Sean" },
    { title: "Hairball - Composer Cover", artist: "Sean, Mike Geno" },
    { title: "Lentement Ver. 2", artist: "Sean" },
    { title: "Lo-Fight - Composer Cover", artist: "Sean, Sock.clip" },
    { title: "Medieval Melody", artist: "Sean" },
    { title: "Off the Perc(ussion)", artist: "Sean" },
    { title: "Everybody's Circulation", artist: "TMABird" },
    { title: "The Walker Instrumental", artist: "Sean, Fitz and The Tantrums" },
    { title: "THOUGHT I WAS DEAD TYPE BEAT", artist: "Tyler, The Creator, Kopia" },
    { title: "Foolhardy", artist: "Rozebud" },
    { title: "Gibberish!!", artist: "coal bones" },
    { title: "Uncanny Valley v2", artist: "Saruky" },
    { title: "Seasonal Shanty but Freegle Forced 7 More Seasonals to Party", artist: "Sean, Others" },
    { title: "Africalypso", artist: "Lagbaja" },
    { title: "Wrong Timing, Inst", artist: "YOGA" },
    { title: "the things you say to me", artist: "POODEE" },
    { title: "badabada", artist: "POODEE" },
    { title: "KABOOM", artist: "bb-panzu" },
    { title: "Dogs Down", artist: "Condard" },
    { title: "Phrygian House Etude", artist: "Leon T" }
].map((song) => ({
    ...song,
    id: song.title,
    file: `${song.title}.mp3`,
}));

function getSongById(id) {
    return SONGS.find((song) => song.id === id) ?? null;
}
